services:
    nginx:
        build:
            context: ${DOCKER_PATH}
            dockerfile: ${DOCKER_PATH}/nginx/Dockerfile
            args:
                USERGROUP: ${USERGROUP}
        volumes:
            - ${SITE_PATH}:/var/www
            - ${DOCKER_PATH}/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - 80:80
            - 443:443
        depends_on:
            - app
        networks:
            - compose
        container_name: nginx
    app:
        build:
            context: ${DOCKER_PATH}
            dockerfile: ${DOCKER_PATH}/app/php-${PHP_VERSION}/Dockerfile
            args:
                USERGROUP: ${USERGROUP}
        volumes:
            - ${SITE_PATH}:/var/www
            - ${DOCKER_PATH}/app/php-${PHP_VERSION}/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ${DOCKER_PATH}/app/php-${PHP_VERSION}/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ${DOCKER_PATH}/app/php-fpm.conf:/usr/local/etc/php-fpm.d/zzzzwww.conf
            - ${DOCKER_PATH}/app/nginx:/etc/nginx/conf.d
        ports:
            - 9000:9000
            - 6001:6001
        environment:
            PHP_IDE_CONFIG: serverName=xdebugServer
            XDEBUG_TRIGGER: testTrig
        depends_on:
            - mysql
        networks:
            - compose
        extra_hosts:
            - host.docker.internal:host-gateway
        container_name: app
    mysql:
        image: mysql:${MYSQL_VERSION}
        restart: always
        volumes:
            - mysql_data:/var/lib/mysql
            - ${DOCKER_PATH}/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        ports:
            - 8102:3306
        environment:
            MYSQL_DATABASE: site
            MYSQL_ROOT_PASSWORD: root
        networks:
            - compose
        container_name: mysql
    memcached:
        image: memcached
        ports:
            - 11211:11211
        networks:
            - compose
        command:
            - --conn-limit=1024
            - --memory-limit=64
            - --threads=4
        container_name: memcached
    node:
        build:
            context: ${DOCKER_PATH}
            dockerfile: ${DOCKER_PATH}/node/Dockerfile
            args:
                NODE_PATH: ${NODE_PATH}
                NODE_VERSION: ${NODE_VERSION}
                USERGROUP: ${USERGROUP}
        volumes:
            - ${SITE_PATH}:/var/www
        ports:
            - 5173:5173
            - 5174:5174
        depends_on:
            - app
        networks:
            - compose
        command: tail -f /dev/null
        container_name: node
    mailhog:
        image: mailhog/mailhog
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - compose
        container_name: mailhog
volumes:
    mysql_data: {}
networks:
    compose:
        driver: bridge
